### ISSUE TITLE
Authentication Failed after short time

### ISSUE THREAD

**Issue by koedijk** [pushrax/node-rcon#25]
Authed!
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Authentication failed
    at Rcon._tcpSocketOnData (C:\Users\joeyk\Desktop\Discord Bot\node_modules\rcon\node-rcon.js:164:28)
    at Socket.<anonymous> (C:\Users\joeyk\Desktop\Discord Bot\node_modules\rcon\node-rcon.js:87:54)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at Rcon._tcpSocketOnData (C:\Users\joeyk\Desktop\Discord Bot\node_modules\rcon\node-rcon.js:164:14)
    at Socket.<anonymous> (C:\Users\joeyk\Desktop\Discord Bot\node_modules\rcon\node-rcon.js:87:54)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by jimnordb** [comment]
https://github.com/BarryCarlyon/node-rcon/commit/70cf321e384d192b9cb411f9fe6de9efd4455f52 fixed it for me.

**Comment by pushrax** [comment]
Neat, thanks for the link. @BarryCarlyon want to submit your patch as a PR?

**Comment by BarryCarlyon** [comment]
Sure. Totally forgot to PR it back!
